### ISSUE TITLE
Failed to load plugin librealsense_gazebo_plugin.so

### ISSUE THREAD

**Issue by Euleeee** [FieldRobotEvent/competition_environment#18]
Hello guys,

i try to start our robot in the competition enviornment, but when i use "docker-compose up" the error message "_[Err] [Plugin.hh:212] Failed to load plugin librealsense_gazebo_plugin.so: librealsense_gazebo_plugin.so: cannot open shared object file: No such file or directory_" shows up. Does anyone know if the error is caused due to the robot container and how to fix it? Is it necessary to define shared plugins in the robot docker-file?

Kind regards

**Comment by Rick-v-E** [comment]
Did you update the simulation container (`docker pull fieldrobotevent/simulation:latest` or `docker pull fieldrobotevent/simulation-cuda:latest`) to the latest version? Any Gazebo plugin should be installed in the simulation container. I have only recently added this plugin.

**Comment by Euleeee** [comment]
Thank you very much!! That was the problem, now it works.
